# Generated by Django 6.0 on 2025-12-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='equipa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogos.equipas'),
        ),
    ]
