# Generated by Django 5.2.3 on 2025-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='jogos',
            field=models.ManyToManyField(blank=True, null=True, to='jogos.equipajogo'),
        ),
    ]
