# Generated by Django 5.2.3 on 2025-07-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_atleta_jogos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='jogos',
        ),
    ]
