# Generated by Django 5.1.5 on 2025-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_remove_atleta_jogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='nome_camisola',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
