# Generated by Django 5.1.5 on 2025-10-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0007_alter_equipas_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='equipa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogos.equipas'),
        ),
    ]
