# Generated by Django 6.0 on 2025-12-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('data', models.DateField(default=None)),
                ('golos_visitado', models.IntegerField(default=0)),
                ('golos_visitante', models.IntegerField(default=0)),
                ('inicio_jogo', models.DateTimeField(blank=True, default=None, null=True)),
                ('pausa', models.BooleanField(blank=True, default=True, null=True)),
                ('fim_jogo', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capitao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitao', to='atletas.atleta')),
                ('suplentes', models.ManyToManyField(blank=True, related_name='suplentes', to='atletas.atleta')),
                ('titulares', models.ManyToManyField(blank=True, related_name='titulares', to='atletas.atleta')),
                ('visitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitado', to='jogos.equipas')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversario', to='jogos.equipas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSubstituição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou', models.DateTimeField(blank=True, default=None, null=True)),
                ('saiu', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_minutos', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogos')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golos', models.IntegerField(default=0)),
                ('inicio', models.DateTimeField(blank=True, default=None, null=True)),
                ('fim', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_minutos', models.FloatField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('em_campo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogos')),
            ],
        ),
    ]
