# Generated by Django 5.2.3 on 2025-07-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_remove_atleta_jogos'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='local',
            new_name='adversario',
        ),
        migrations.RemoveField(
            model_name='equipajogo',
            name='suplente',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='nome',
        ),
        migrations.AddField(
            model_name='equipajogo',
            name='assistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipajogo',
            name='atleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipajogo',
            name='golos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogos',
            name='casa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
