# Generated by Django 5.1.5 on 2025-10-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0002_equipas_rename_local_jogos_adversario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='adversario',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='casa',
        ),
        migrations.AddField(
            model_name='jogos',
            name='capitao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capitao', to='atletas.atleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogos',
            name='golos_visitado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogos',
            name='golos_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogos',
            name='suplentes',
            field=models.ManyToManyField(related_name='suplentes', to='atletas.atleta'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='titulares',
            field=models.ManyToManyField(related_name='titulares', to='atletas.atleta'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='visitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitado', to='jogos.equipas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogos',
            name='visitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adversario', to='jogos.equipas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogos',
            name='data',
            field=models.DateField(default=None),
        ),
        migrations.DeleteModel(
            name='EquipaJogo',
        ),
    ]
