# Generated by Django 5.1.5 on 2025-10-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0003_remove_jogos_adversario_remove_jogos_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='jornada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstatisticaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golos', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogos')),
            ],
        ),
    ]
