# Generated by Django 5.1.5 on 2025-10-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0004_jogos_jornada_estatisticajogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipas',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta'),
        ),
    ]
