# Generated by Django 5.1.5 on 2025-10-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0005_equipas_atleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipas',
            name='atleta',
        ),
       
    ]
