# Generated by Django 5.1.5 on 2025-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_nome_camisola'),
        ('jogos', '0006_remove_equipas_atleta_equipas_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipas',
            name='atleta',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipas', to='atletas.atleta'),
        ),
    ]
