# Generated by Django 5.1.5 on 2025-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_atleta_equipa'),
        ('jogos', '0007_alter_equipas_atleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipas',
            name='atleta',
        ),
        migrations.AlterField(
            model_name='jogos',
            name='suplentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='suplentes', to='atletas.atleta'),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='titulares',
            field=models.ManyToManyField(blank=True, null=True, related_name='titulares', to='atletas.atleta'),
        ),
    ]
