# Generated by Django 5.1.5 on 2025-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_atleta_equipa'),
        ('jogos', '0008_remove_equipas_atleta_alter_jogos_suplentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='suplentes',
            field=models.ManyToManyField(blank=True, related_name='suplentes', to='atletas.atleta'),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='titulares',
            field=models.ManyToManyField(blank=True, related_name='titulares', to='atletas.atleta'),
        ),
    ]
