# Generated by Django 5.1.5 on 2025-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0009_alter_jogos_suplentes_alter_jogos_titulares'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticajogo',
            name='fim',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='estatisticajogo',
            name='inicio',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='estatisticajogo',
            name='total_minutos',
            field=models.FloatField(default=0),
        ),
    ]
