# Generated by Django 5.1.5 on 2025-10-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_estatisticajogo_fim_estatisticajogo_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticajogo',
            name='fim',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='estatisticajogo',
            name='inicio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
