# Generated by Django 5.1.5 on 2025-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0011_alter_estatisticajogo_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='fim_jogo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jogos',
            name='inicio_jogo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jogos',
            name='segunda_parte',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
