# Generated by Django 5.1.5 on 2025-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0012_jogos_fim_jogo_jogos_inicio_jogo_jogos_segunda_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticajogo',
            name='em_campo',
            field=models.BooleanField(default=False),
        ),
    ]
