# Generated by Django 5.1.5 on 2025-11-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_atleta_equipa'),
        ('jogos', '0013_estatisticajogo_em_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSubstituição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou', models.DateTimeField(blank=True, default=None, null=True)),
                ('saiu', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_minutos', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogos')),
            ],
        ),
    ]
