# Generated by Django 5.1.5 on 2025-12-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0014_historicosubstituição'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='fim_primeira_parte',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jogos',
            name='inicio_segunda_parte',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
