# Generated by Django 5.1.5 on 2025-12-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0015_jogos_fim_primeira_parte_jogos_inicio_segunda_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='pausa',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
