# Generated by Django 5.1.5 on 2025-12-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0016_jogos_pausa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='fim_primeira_parte',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='inicio_segunda_parte',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='segunda_parte',
        ),
    ]
