# Generated by Django 5.2.3 on 2025-06-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_atleta_jogos'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EncomendaEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('equipamento', models.ManyToManyField(to='equipamentos.equipamentos')),
            ],
        ),
    ]
