# Generated by Django 5.2.3 on 2025-07-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamentos_data_entrega_encomendaequipamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomendaequipamentos',
            old_name='Atleta',
            new_name='atleta',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='entregue',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='encomendaequipamentos',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomendaequipamentos',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encomendaequipamentos',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tamanho'),
        ),
    ]
