# Generated by Django 5.1.1 on 2025-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_remove_encomendaequipamentos_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomendaequipamentos',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='encomendaequipamentos',
            name='equipamento',
            field=models.ManyToManyField(to='equipamentos.equipamentos'),
        ),
    ]
