# Generated by Django 5.1.1 on 2025-07-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_remove_atleta_jogos'),
        ('equipamentos', '0005_remove_encomendaequipamentos_equipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('tamanho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.encomenda')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamentos')),
            ],
        ),
        migrations.DeleteModel(
            name='EncomendaEquipamentos',
        ),
    ]
