# Generated by Django 5.1.1 on 2025-07-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_encomenda_encomendaitem_delete_encomendaequipamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomendaitem',
            name='encomenda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.encomenda'),
        ),
    ]
