# Generated by Django 5.1.1 on 2025-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_alter_encomendaitem_encomenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomendaitem',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='encomendaitem',
            name='equipamento',
            field=models.ManyToManyField(to='equipamentos.equipamentos'),
        ),
    ]
